---
- hosts: all
  become: true

  tasks:
    - git:
        repo: 'https://github.com/cea-hpc/modules.git'
        dest: /home/ri22bytu/modules
        clone: yes
    - shell: ./configure && make && make install
      args:
        chdir: /home/ri22bytu/modules
