---
- hosts: all
  become: true

  tasks:
    - name: copy
      shell: cp /opt/apps/slurm/17.02.9/etc/slurm.conf /etc/slurm.conf
    - name: enable_slurm
      service: name=slurmd enabled=yes state=started
